version: "3"

services: 
  db:
    image: postgres
    environment: 
      POSTGRES_HOST_AUTH_METHOD: "trust"
    env_file:
      - .env
      
  dj:
    container_name: dj
    build: django
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./django:/code
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db